[package]
name = "ftp-server"
authors = ["Pablo Hernandez (@Hadronomy)"]
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
clap-help = "1.2.0"
color-eyre = "0.6.2"
crossterm = "0.27.0"
eyre = "0.6.8"
eza = { version = "0.18.14", default-features = false }
libc = "0.2.147"
miette = { version = "7.2.0", features = ["fancy"] }
nom = "7.1.3"
nom-supreme = "0.8.0"
num-derive = "0.4.0"
num-integer = "0.1.45"
num-traits = "0.2.16"
ratatui = "0.26.1"
termimad = "0.29.1"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.37"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "std", "ansi", "env-filter"] }
tui-logger = { version = "0.11.0", features = [
    "tracing",
    "tracing-subscriber",
    "crossterm",
    "tracing-support",
] }
